Extension Manager
Gandi-IDE/gandi-plugins pull request #54
Opened 2024-06-09 13:51 UTC by fath11

feat:
- the ability to delete extensions

unfinished:
- reordering extensions, this PR won't be set as a draft because this function is commented out in the code. When it is ready for release another PR will be made. The reason for this is that I meant to implement reordering before opening a PR but due to high demands, I decided to open this PR first.

2024-06-11 06:12 UTC, zxq142857 commented
This idea is great. We recently discussed making a plugin like this.

2024-06-11 06:49 UTC, zxq142857 reviewed
It is still necessary to ensure proper code formatting checks.

2024-06-11 06:49 UTC, zxq142857 commented on src/plugins/plugins-manager/index.tsx
> +  "extension-manager",
This plugin should not be installed by default.

2024-06-11 06:49 UTC, zxq142857 commented on src/plugins/extension-manager/styles.less
> +  padding-bottom: 1px;
"Setting it to 0 will make it look more centered vertically.

2024-06-11 06:49 UTC, zxq142857 commented on src/plugins/extension-manager/index.tsx
> +const ExtensionManager: React.FC<PluginContext & { vm: VirtualMachineWithExtensions }> = ({ intl, utils, vm, redux }) => {
I will complete the TS definitions for the VM as soon as possible.

2024-06-11 06:49 UTC, zxq142857 commented on src/plugins/extension-manager/index.tsx
> +  const getExtensionInfoById = (id: string) => {
This still doesn't perfectly solve the issue of translating the names of built-in plugins.

2024-06-11 06:49 UTC, zxq142857 commented on src/plugins/extension-manager/index.tsx
> +      info = {info: {extensionId: id, name: id}}
Replace `info:·{·extensionId:·id,·name:·id·}}` with `·info:·{·extensionId:·id,·name:·id·}·};`

2024-06-11 06:50 UTC, zxq142857 commented
After reviewing your code, it seems you've encountered some challenging issues. You can't retrieve information for all plugins (including the six built-in extensions and custom extensions). Therefore, I think an API should be provided to solve this problem.

2024-06-11 06:52 UTC, zxq142857 commented
The translation of the plugin name still needs to be added to l10n. In Chinese, it can be called "插件管理", with a description: "管理你所有已安装的插件" (Manage all your installed plugins).

2024-06-11 13:12 UTC, zxq142857 commented on src/plugins/extension-manager/index.tsx
> +  const getExtensionInfoById = (id: string) => {
> This still doesn't perfectly solve the issue of translating the names of built-in plugins.

You can now get all extension information through the getAllExtensionInfo method in utils.

2024-06-15 04:34 UTC, fath11 commented
New update: all the dragging stuff are removed and multi select is a thing now

2024-06-16 07:51 UTC, MoreBugOfDog requested changes

2024-06-16 07:51 UTC, MoreBugOfDog commented on src/l10n/zh-cn.json
> +  "plugins.ExtensionManager.intro": "管理你所有已安装的插件。"
![image](https://github.com/Gandi-IDE/gandi-plugins/assets/121487216/c6cedffe-cffb-4e2a-935f-1d3a392bfe26)
This plugin is used to manage the installation and uninstallation of extensions
So I10n should read "拓展" not “插件”

2024-06-16 12:54 UTC, fath11 commented on src/l10n/zh-cn.json
> +  "plugins.ExtensionManager.intro": "管理你所有已安装的插件。"
zxq made the L10n, i just copy paste what he said above

2024-06-19 03:10 UTC, merged